apt_type_sortie_audience_sap = AppointmentType.find_or_create_by!(name: "Sortie d'audience SAP")
apt_type_rdv_suivi_jap = AppointmentType.find_or_create_by!(name: 'RDV de suivi JAP')
apt_type_rdv_suivi_spip = AppointmentType.find_or_create_by!(name: "RDV de suivi SPIP")
apt_type_sortie_audience_spip = AppointmentType.find_or_create_by!(name: "Sortie d'audience SPIP")
apt_type_sap_ddse = AppointmentType.find_or_create_by!(name: "SAP DDSE")

NotificationType.create!(appointment_type: apt_type_sortie_audience_sap, role: :summon, template: "Vous êtes convoqué, merci de venir.", is_default: true)
NotificationType.create!(appointment_type: apt_type_sortie_audience_sap, role: :reminder, template: "RAPPEL Vous êtes convoqué, vraiment il faut venir.", reminder_period: :two_days, is_default: true)
NotificationType.create!(appointment_type: apt_type_sortie_audience_sap, role: :cancelation, template: "Finalement non, c'est pas la peine.", is_default: true)
NotificationType.create!(appointment_type: apt_type_sortie_audience_sap, role: :no_show, template: "Vous n'êtes pas venu :(", is_default: true)
NotificationType.create!(appointment_type: apt_type_sortie_audience_sap, role: :reschedule, template: "Changement du rdv de date X a date Y.", is_default: true)

NotificationType.create!(appointment_type: apt_type_rdv_suivi_jap, role: :summon, template: "Vous êtes convoqué, merci de venir.", is_default: true)
NotificationType.create!(appointment_type: apt_type_rdv_suivi_jap, role: :reminder, template: "RAPPEL Vous êtes convoqué, vraiment il faut venir.", reminder_period: :two_days, is_default: true)
NotificationType.create!(appointment_type: apt_type_rdv_suivi_jap, role: :cancelation, template: "Finalement non, c'est pas la peine.", is_default: true)
NotificationType.create!(appointment_type: apt_type_rdv_suivi_jap, role: :no_show, template: "Vous n'êtes pas venu :(", is_default: true)
NotificationType.create!(appointment_type: apt_type_rdv_suivi_jap, role: :reschedule, template: "Changement du rdv de date X a date Y.", is_default: true)

NotificationType.create!(appointment_type: apt_type_rdv_suivi_spip, role: :summon, template: "Vous êtes convoqué, merci de venir.", is_default: true)
NotificationType.create!(appointment_type: apt_type_rdv_suivi_spip, role: :reminder, template: "RAPPEL Vous êtes convoqué, vraiment il faut venir.", reminder_period: :two_days, is_default: true)
NotificationType.create!(appointment_type: apt_type_rdv_suivi_spip, role: :cancelation, template: "Finalement non, c'est pas la peine.", is_default: true)
NotificationType.create!(appointment_type: apt_type_rdv_suivi_spip, role: :no_show, template: "Vous n'êtes pas venu :(", is_default: true)
NotificationType.create!(appointment_type: apt_type_rdv_suivi_spip, role: :reschedule, template: "Changement du rdv de date X a date Y.", is_default: true)

NotificationType.create!(appointment_type: apt_type_sortie_audience_spip, role: :summon, template: "Vous êtes convoqué à votre sortie d'audience SPIP, merci de venir.", is_default: true)
NotificationType.create!(appointment_type: apt_type_sortie_audience_spip, role: :reminder, template: "RAPPEL Vous êtes convoqué à votre sortie d'audience SPIP, vraiment il faut venir.", reminder_period: :two_days, is_default: true)
NotificationType.create!(appointment_type: apt_type_sortie_audience_spip, role: :cancelation, template: "Finalement non, c'est pas la peine.", is_default: true)
NotificationType.create!(appointment_type: apt_type_sortie_audience_spip, role: :no_show, template: "Vous n'êtes pas venu :(", is_default: true)
NotificationType.create!(appointment_type: apt_type_sortie_audience_spip, role: :reschedule, template: "Changement du rdv de date X a date Y.", is_default: true)

NotificationType.create!(appointment_type: apt_type_sap_ddse, role: :summon, template: "Vous êtes convoqué à votre rdv SAP DDSE, merci de venir.", is_default: true)
NotificationType.create!(appointment_type: apt_type_sap_ddse, role: :reminder, template: "RAPPEL Vous êtes convoqué à votre rdv SAP DDSE, vraiment il faut venir.", reminder_period: :two_days, is_default: true)
NotificationType.create!(appointment_type: apt_type_sap_ddse, role: :cancelation, template: "Finalement non, c'est pas la peine.", is_default: true)
NotificationType.create!(appointment_type: apt_type_sap_ddse, role: :no_show, template: "Vous n'êtes pas venu :(", is_default: true)
NotificationType.create!(appointment_type: apt_type_sap_ddse, role: :reschedule, template: "Changement du rdv de date X a date Y.", is_default: true)