// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AppointmentExtraFieldDisplayController from "./appointment_extra_field_display_controller"
application.register("appointment-extra-field-display", AppointmentExtraFieldDisplayController)

import AppointmentNewController from "./appointment_new_controller"
application.register("appointment-new", AppointmentNewController)

import DisableWhenAbymeLimitReachedController from "./disable_when_abyme_limit_reached_controller"
application.register("disable-when-abyme-limit-reached", DisableWhenAbymeLimitReachedController)

import SearchCitiesController from "./search_cities_controller"
application.register("search-cities", SearchCitiesController)

import SearchCitiesResultsController from "./search_cities_results_controller"
application.register("search-cities-results", SearchCitiesResultsController)

import SearchConvictsController from "./search_convicts_controller"
application.register("search-convicts", SearchConvictsController)

import SearchUsersController from "./search_users_controller"
application.register("search-users", SearchUsersController)

import SearchUsersResultsController from "./search_users_results_controller"
application.register("search-users-results", SearchUsersResultsController)

import TableUpdateFieldController from "./table_update_field_controller"
application.register("table-update-field", TableUpdateFieldController)

import SearchController from "./search_controller"
application.register("search", SearchController)
