AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - bin/**/*
    - scripts/**/*
    - config/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
    - .git/**/*
    - Guardfile
    - Rakefile
    - config.ru
    - cli
    - spec/spec_helper.rb
    - spec/rails_helper.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - app/models/notification.rb
    - app/models/appointment.rb
    - app/controllers/admin/seeds_controller.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - app/models/appointment.rb
    - app/models/notification.rb

Layout/MultilineMethodCallIndentation:
  Exclude:
    - spec/**/*

Style/FormatStringToken:
  Exclude:
    - spec/services/notification_factory_spec.rb

Style/NumericLiteralPrefix:
  Exclude:
    - spec/services/slot_type_factory_spec.rb

Style/SymbolArray:
  Exclude:
    - app/controllers/**/*
    - app/models/notification.rb

Style/IfUnlessModifier:
  Exclude:
    - app/models/appointment.rb

Metrics/MethodLength:
  Max: 20
  Exclude:
    - app/services/notification_factory.rb
    - app/services/slot_type_factory.rb
    - app/helpers/users_helper.rb
    - app/controllers/home_controller.rb
    - app/services/history_item_factory.rb
    - app/controllers/appointments_controller.rb
    - app/controllers/appointments_bookings_controller.rb
    - app/controllers/admin/import_convicts_controller.rb
    - app/controllers/admin/users_controller.rb
    - app/jobs/appi_import_job.rb
    - app/controllers/admin/seeds_controller.rb

Metrics/ClassLength:
  Max: 300
  Exclude:
    - app/models/appointment.rb
    - app/models/convict.rb
    - app/models/user.rb
    - app/controllers/appointments_controller.rb
    - app/controllers/convicts_controller.rb

Metrics/AbcSize:
  Exclude:
    - app/policies/convict_policy.rb
    - app/policies/place_policy.rb
    - app/policies/slot_policy.rb
    - app/policies/appointment_policy.rb
    - app/policies/agenda_policy.rb
    - app/controllers/appointments_controller.rb
    - app/controllers/appointments_bookings_controller.rb
    - app/controllers/home_controller.rb
    - app/services/history_item_factory.rb
    - app/controllers/admin/import_convicts_controller.rb
    - app/controllers/admin/users_controller.rb
    - app/jobs/appi_import_job.rb
    - app/controllers/admin/seeds_controller.rb

Layout/LineLength:
  Exclude:
    - app/dashboards/**/*

Style/ClassAndModuleChildren:
  Exclude:
    - app/dashboards/**/*

Style/IfWithBooleanLiteralBranches:
  Exclude:
    - app/policies/appointment_policy.rb

Style/ExplicitBlockArgument:
  Exclude:
    - app/controllers/application_controller.rb
