AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - bin/**/*
    - config/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
    - .git/**/*
    - Guardfile
    - Rakefile
    - config.ru
    - cli
    - spec/spec_helper.rb
    - spec/rails_helper.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - app/models/notification.rb
    - app/models/appointment.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - app/models/appointment.rb
    - app/models/notification.rb

Layout/MultilineMethodCallIndentation:
  Exclude:
    - spec/**/*

Style/FormatStringToken:
  Exclude:
    - spec/services/notification_factory_spec.rb

Style/NumericLiteralPrefix:
  Exclude:
    - spec/services/slot_type_factory_spec.rb

Style/SymbolArray:
  Exclude:
    - app/controllers/**/*
    - app/models/notification.rb

Style/IfUnlessModifier:
  Exclude:
    - app/models/appointment.rb

Metrics/MethodLength:
  Exclude:
    - app/services/notification_factory.rb
    - app/services/slot_type_factory.rb
    - app/helpers/users_helper.rb
    - app/controllers/home_controller.rb

Metrics/ClassLength:
  Exclude:
    - app/models/appointment.rb

Metrics/AbcSize:
  Exclude:
    - app/policies/convict_policy.rb
    - app/policies/place_policy.rb
    - app/policies/slot_policy.rb
    - app/policies/appointment_policy.rb
    - app/controllers/appointments_controller.rb
    - app/controllers/home_controller.rb
