AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - bin/**/*
    - config/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
    - .git/**/*
    - Guardfile
    - Rakefile
    - config.ru
    - spec/spec_helper.rb
    - spec/rails_helper.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - app/models/notification.rb
    - app/models/appointment.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - app/models/appointment.rb
    - app/models/notification.rb

Layout/MultilineMethodCallIndentation:
  Exclude:
    - spec/**/*

Style/FormatStringToken:
  Exclude:
    - spec/services/notification_factory_spec.rb

Style/WordArray:
  Exclude:
    - app/policies/appointment_policy.rb

Style/SymbolArray:
  Exclude:
    - app/controllers/**/*
    - app/models/notification.rb

Style/IfUnlessModifier:
  Exclude:
    - app/models/appointment.rb

Metrics/MethodLength:
  Exclude:
    - app/services/notification_factory.rb

Metrics/AbcSize:
  Exclude:
    - app/policies/appointment_policy.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - app/policies/appointment_policy.rb

Metrics/PerceivedComplexity:
  Exclude:
    - app/policies/appointment_policy.rb
