version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'msj'
      POSTGRES_USER: 'msj'
    ports:
      - "5432:5432"
  web:
    environment:
      DATABASE_URL: 'db'
    build: .
    volumes:
      - "./:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
