#!/usr/bin/env bash

echo ""
echo "You are deploying these commits to production :"
echo ""
git --no-pager log --oneline --no-decorate --abbrev-commit master..develop
echo ""
read -p "Do you confirm ? (y/n)" -n 1

if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo ""
  echo "Merge develop in master"
  git checkout master
  git merge develop --no-edit

  CONFLICTS=$(git ls-files -u | wc -l)
  if [ "$CONFLICTS" -gt 0 ] ; then
    echo "There is a merge conflict. Aborting."
    git merge --abort
    exit 1
  fi

  git push origin master
  git checkout develop
  echo "Push to Scalingo prod"
  git push scalingo-prod master
  echo "Run database migrations in production"
  scalingo -a mon-suivi-justice-prod --region osc-secnum-fr1 run rails db:migrate
  echo ""
  echo "Production deployed"
  echo "Push to Scalingo demo"
  git push scalingo-demo master
  echo "Run database setup in demo"
  scalingo -a mon-suivi-justice-demo --region osc-secnum-fr1 run rails db:migrate
  echo ""
  echo "Demo deployed"
fi
